# Generated by Django 4.1.4 on 2023-06-13 04:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ciclos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocolo", models.CharField(max_length=10)),
                ("tecnica", models.CharField(max_length=10)),
                ("transferido", models.BooleanField()),
                ("nacimiento", models.BooleanField()),
                ("cancelado", models.BooleanField()),
                ("embarazo_bioquimico", models.BooleanField()),
                ("embarazo_clinico", models.BooleanField()),
                ("embarazo_multiple", models.BooleanField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "ciclo", "verbose_name_plural": "ciclos",},
        ),
        migrations.CreateModel(
            name="Dia2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad_celulas", models.IntegerField()),
                ("porcentaje_fragmentacion", models.FloatField()),
                ("simetria", models.BooleanField()),
            ],
            options={"verbose_name": "dia2", "verbose_name_plural": "dias2",},
        ),
        migrations.CreateModel(
            name="Dia3",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad_celulas", models.IntegerField()),
                ("porcentaje_fragmentacion", models.FloatField()),
                ("simetria", models.BooleanField()),
            ],
            options={"verbose_name": "dia3", "verbose_name_plural": "dias3",},
        ),
        migrations.CreateModel(
            name="Dia5",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blastocisto", models.BooleanField()),
                (
                    "grado_expancion",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ]
                    ),
                ),
                (
                    "mci",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                (
                    "trofoectodermo",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
            ],
            options={"verbose_name": "dia5", "verbose_name_plural": "dias5",},
        ),
        migrations.CreateModel(
            name="Pacientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("edad", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=15)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "paciente", "verbose_name_plural": "pacientes",},
        ),
        migrations.CreateModel(
            name="Embrion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transferenciabilidad", models.BooleanField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCiclosPacientes.ciclos",
                    ),
                ),
                (
                    "dia2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCiclosPacientes.dia2",
                    ),
                ),
                (
                    "dia3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCiclosPacientes.dia3",
                    ),
                ),
                (
                    "dia5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCiclosPacientes.dia5",
                    ),
                ),
            ],
            options={"verbose_name": "embrion", "verbose_name_plural": "embriones",},
        ),
        migrations.AddField(
            model_name="ciclos",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ciclos",
                to="gestionCiclosPacientes.pacientes",
            ),
        ),
    ]
