# Generated by Django 4.1.4 on 2023-02-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='modelos'),
        ),
    ]
