# Generated by Django 4.1.4 on 2023-03-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="files/embriones"
                    ),
                ),
            ],
            options={"verbose_name": "embrion", "verbose_name_plural": "embriones",},
        ),
    ]
