# Generated by Django 4.1.1 on 2022-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0003_alter_postpdf_contenido_alter_postpdf_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpdf',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
